import "@/styles/globals.css";
import Head from "next/head";

import { CssBaseline } from "@mui/material";
import Layout from "@/components/Layout/Layout";
import getLPTheme from "@/data/getLPTheme";
import { ThemeProvider, createTheme } from "@mui/material/styles";

const App = ({ Component, pageProps }) => {
  const LPtheme = createTheme(getLPTheme("light"));
  return (
    <>
      <Head>
        <title>Game.DevZone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={LPtheme}>
        <CssBaseline />
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ThemeProvider>
    </>
  );
};

export default App;
